FROM mcr.microsoft.com/dotnet/runtime:5.0

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/net5.0/publish /app

ENV TZ=Europe/Brussels
ENV KEY_VAULT=...
ENV CLIENT_ID=...
ENV CLIENT_SECRET=...
ENV ARENA_SIZE=...
ENV ELASTIC_HOST=...

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Processor.dll"]